### PR TITLE
cdrtools: update to 3.02a06

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
Hi @tpgxyz!
I have recently uploaded `cdrtools-3.02a06.tar.bz2` to the file-store and updated `.abf.yml` and `cdrtools.spec` to release 3.02a06.
BTW, cdrtools/cdda2wav has gained pulseaudio support with release 3.02a01: if libpulse and its headers are available at build time then `cdda2wav -echo` will try to use pulseaudio and fall back to libasound. I have therefore added an optional dependency on libpulse.
Shall I merge this PR? Thanks!

**Comment by fbrosson** [comment]
I've already uploaded cdrtools-**3.02a05**.tar.bz2 to the file store.
I haven't set up a box with OpenMandriva yet, so I cannot check whether everything is OK.
If someone would be willing to test this, then I would be very gratefull.
BTW, if OMA wants to wait until 3.02 (final) is released then please let me know so that I won't update this PR (nor upload newer 3.02aXX tarballs anymore) until 3.02 is out.
Thanks!

**Comment by fbrosson** [comment]
Hi @tpgxyz !
I have recently squashed the commits in this PR, fixed the merge conflicts and rebased it against master. So if you would like to test the spec for version 3.02a06, it's there, ready for a merge ;-)
**Important**: I already uploaded the tarball to the file server a long time ago, but **I did not try** to build it on OpenMandriva.

**Comment by tpgxyz** [comment]
@fbrosson Hi, thanks for your work, You can commit directly to this repository if you like.

**Comment by fbrosson** [comment]
Cool, thanks!
BTW, I know I can commit directly, but I did not dare to do so because I was not 100% sure of the small changes I made to the spec file, especially those about the **`bcond_with alsa`** and **`bcond_with pulse`**.

**Pull request merged**
